openapi: 3.0.0
info:
  title: AI-Book RAG Chatbot API
  version: 1.0.0
  description: API for the Retrieval-Augmented Generation (RAG) chatbot integrated with the AI-Book Docusaurus textbook.

servers:
  - url: /api/v1
    description: RAG Chatbot API Server

paths:
  /chat:
    post:
      summary: Send a chat message to the RAG chatbot
      operationId: postChatMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatbotResponse'
        '400':
          description: Invalid request payload
        '500':
          description: Internal server error

  /ask-selected:
    post:
      summary: Ask a question based on selected text from the textbook
      operationId: postAskSelected
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskSelectedRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatbotResponse'
        '400':
          description: Invalid request payload
        '500':
          description: Internal server error

components:
  schemas:
    ChatMessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's question or chat message.
          example: "What is ROS 2?"

    AskSelectedRequest:
      type: object
      required:
        - selected_text
      properties:
        selected_text:
          type: string
          description: The text selected by the user from the Docusaurus textbook.
          example: "ROS 2 (Robot Operating System) is a flexible framework for writing robot software."
        context_id:
          type: string
          description: Optional identifier for the specific Docusaurus page or section where the text was selected.
          example: "/docs/module1/intro"

    ChatbotResponse:
      type: object
      required:
        - answer
      properties:
        answer:
          type: string
          description: The answer generated by the RAG chatbot.
          example: "ROS 2 is a set of software libraries and tools that help you build robot applications."
        source_references:
          type: array
          items:
            type: string
          description: Optional list of references (e.g., Docusaurus page URLs, section IDs) from which the answer was derived.
          example: ["/docs/module1/ros2-overview", "/docs/glossary#ros2"]
